### ISSUE TITLE
Missing Code!

### ISSUE THREAD

**Issue by makenb** [margyle/heyMugsy#1]

**Comment by margyle** [comment]
Code drops in March, 2018.

**Comment by margyle** [comment]
Code drops in March, 2018.

**Comment by makenb** [comment]
Oh cool! Is the hardware design open as well?

**Comment by margyle** [comment]
Yup, the parts list and build manual will be coming out then as well. It may not be 100% complete at that point but all basic functionality will be available. The plan is to have completed units and kits for sale as well as the fully open source build option for folks who want to completely DIY it. So as I'm working on the units/kits I'll be pushing the source and build instructions on the same timeline so there wont be any delay between the three options. Let me know know if you have any other questions.

**Comment by makenb** [comment]
Thanks for your response. I stumbled across this project while researching "diy arduino coffee machines" and it sounds like a good starting point for what I want to build. Do you have any further information? Do you have a working prototype? Is it documented elsewhere? If you need help like beta testing or anything I may be able to help out.

**Comment by margyle** [comment]
Yeah, Ive been showing off the prototype all over and giving talks about it. Just gave a talk at Euro Maker Faire in Rome and Mugsy received an editors choice award at the World Maker Faire in NYC. Here is an ok-ish full shot of the prototype: https://www.instagram.com/p/BZoJP-ADemn 

Some write ups and interviews here:
https://blog.hackster.io/mugsy-is-the-coffee-maker-of-your-dreams-built-with-a-raspberry-pi-and-arduino-143b17e921dc
https://whatsittech.com/2017/10/13/self-taught-programmer-came-create-mugsy-automatic-coffee-maker/
https://makezine.com/2017/09/28/edible-innovations-text-machine-will-get-you-coffee/
Pretty good info in this q and a on reddit: https://www.reddit.com/r/raspberry_pi/comments/72kdqp/my_pi_powered_coffee_robot_snagged_an_editors/

Prototype is just about 100% complete, just doing fit and finish type work and code. I post my day to day working pics/vids and info to instagram.com/marrrgyle although theres a lot of non-mugsy arduino and pi stuff on there. I also post demos and pics to instagram.com/heymugsy but it's not as active while I'm in head down dev mode. Both have some great mugsy vids and pics. I basically post everything as Im working on it.

I'll definitely need help with beta testing and will be opening up the github to contributors. Best place for updates between now and March is the Instagram accounts and the Facebook page- facebook.com/heymugsy.  Theres also a mailing list subscription at heymugsy. com.

**Comment by StevenGFX** [comment]
Good stuff! Thanks @margyle! I'm excited!

**Comment by margyle** [comment]
Thanks @StevenGFX :)
